// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQUrymNaslgtwjhCzMk01ZUBQPBDdMlM',
    appId: '1:93713242740:android:9e66701b306f74d6af4f21',
    messagingSenderId: '93713242740',
    projectId: 'fruitmarket-2c64c',
    storageBucket: 'fruitmarket-2c64c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5p8RxtdOIgtsyEz50XFjNpZKHlUnw8TM',
    appId: '1:93713242740:ios:a959b60076b76e50af4f21',
    messagingSenderId: '93713242740',
    projectId: 'fruitmarket-2c64c',
    storageBucket: 'fruitmarket-2c64c.appspot.com',
    androidClientId: '93713242740-qtluoac0g1am11h8nv3mml78eogii5i4.apps.googleusercontent.com',
    iosClientId: '93713242740-gt2r92mifd7jnqki952mcn8qklb1fm55.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

}